package com.trm.daylighter.feature.day

enum class DayTestTags {
  EMPTY_LOCATIONS_CARD,
  WITHOUT_DATA_LOCATIONS_CHART,
  LOADING_LOCATIONS_PROGRESS_INDICATOR,
  TOP_APP_BAR,
  DRAWER_MENU_ICON_BUTTON,
  NAVIGATION_BAR,
  NAVIGATION_SUNRISE_ITEM,
  NAVIGATION_SUNSET_ITEM,
  NAVIGATION_RAIL
}
